### PR TITLE
add gff_util

### PR DESCRIPTION
**Pull request by bgruening**
xref: https://github.com/galaxyproject/gops/pull/4

ping @nsoranzo

### CODE REVIEW

**Comment by nsoranzo** [comment]
:+1:

**Comment by bgruening** [comment]
@martenson can you merge this and maybe do a release?

**Comment by martenson** [comment]
release: https://github.com/galaxyproject/gops/releases/tag/v1.1.0

**Comment by bgruening** [comment]
Thanks @martenson!

**Pull request merged**
