### PR TITLE
Add gff_utils

### PR DESCRIPTION
**Pull request by bgruening**
xref: https://github.com/galaxyproject/tools-devteam/pull/456

### CODE REVIEW

**Comment by nsoranzo** [comment]
Thanks @bgruening, 3 comments:
- we should probably use the more recent version from Galaxy (which has been ported to Python3) instead of this one (which is from https://github.com/galaxyproject/tools-devteam/blob/master/tool_collections/gops/utils/gff_util.py )
- the file should be moved to ` lib/galaxy/datatypes/util/gff_util.py` as in Galaxy
- since only `GFFReaderWrapper` class is used in tools-devteam, I was able to strip this file down from 460 to 312 lines, if it is of interest, see https://gist.github.com/nsoranzo/c0d08c100147bb6478a61648416b3e88

**Comment by bgruening** [comment]
@nsoranzo push it into this one here! Really feel free to just apply your very valuable comments directly! :)

**Comment by bgruening** [comment]
Not that I will not do it, but sometimes it feels faster if you just go ahead :)

**Comment by nsoranzo** [comment]
Some changes may be up for discussion (2nd and 3rd point above), but anyway I don't have write access to this repo!

**Comment by bgruening** [comment]
@nsoranzo I created an other PR, so this one is then obsolete. I also don't have commit access to this repo, so we need someone else to merge.

**Comment by martenson** [comment]
@bgruening @nsoranzo now all committers have access here

**Comment by nsoranzo** [comment]
Thanks @martenson!

**Pull request closed without merging**
